spec:
  projectName: gitops-repo
  releaseName: p5js-sketches  
  namespace: p5js-sketches
  
  # Security configuration
  security:
    runAsNonRoot: true
    runAsUser: 101  # nginx user
    runAsGroup: 101
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  # Service configuration  
  service:
    type: 'LoadBalancer'
    port: 80
    annotations:
      external-dns.alpha.kubernetes.io/hostname: 'p5js-sketches.metallb.k8s.goldentooth.net'
      metallb.universe.tf/address-pool: 'primary'

# Server configuration
server:
  image: ghcr.io/goldentooth/p5js-sketches:main-1cb3b00
  replicas: 1
  resources:
    limits:
      memory: '64Mi'
      cpu: '100m'
    requests:
      memory: '32Mi'
      cpu: '50m'
    
# Performance tuning for Pi hardware
nginx:
  workerProcesses: 'auto'
  workerConnections: 1024
  keepaliveTimeout: 65
  clientMaxBodySize: '1m'