apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: p5js-sketches-controller
  labels:
    app: p5js-sketches
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]