apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: p5js-sketches-controller
  labels:
    app: p5js-sketches
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: p5js-sketches-controller
subjects:
- kind: ServiceAccount
  name: p5js-sketches-controller
  namespace: {{ .Values.spec.namespace }}