apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.spec.namespace }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;
        
        # Health check endpoint
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Serve sketches from subdirectories
        location / {
            try_files $uri $uri/ =404;
            
            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            # Special handling for p5.js sketches
            location ~ ^/([^/]+)/?$ {
                try_files $uri $uri/ /$1/index.html =404;
            }
        }
        
        # Serve custom gallery index.html at root
        location = / {
            try_files /index.html =404;
        }
    }