apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.spec.namespace }}
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        
        # Health check endpoint (HTTP only, no redirect)
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Redirect all other traffic to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }
    
    server {
        listen 8443 ssl;
        http2 on;
        server_name {{ index .Values.spec.service.annotations "external-dns.alpha.kubernetes.io/hostname" }};
        root /usr/share/nginx/html;
        index index.html;
        
        # SSL configuration
        ssl_certificate /etc/ssl/certs/tls.crt;
        ssl_certificate_key /etc/ssl/private/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        
        # Health check endpoint (also available on HTTPS)
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Serve sketches from subdirectories
        location / {
            try_files $uri $uri/ =404;
            
            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                expires 1y;
                add_header Cache-Control "public, immutable";
            }
            
            # Special handling for p5.js sketches
            location ~ ^/([^/]+)/?$ {
                try_files $uri $uri/ /$1/index.html =404;
            }
        }
        
        # Serve custom gallery index.html at root
        location = / {
            try_files /index.html =404;
        }
    }