apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.spec.namespace }}
data:
  default.conf: |
    # Map to determine if request should be served or redirected
    map $host $serve_content {
        default 0;
        "p5js-sketches.metallb.k8s.goldentooth.net" 1;
    }
    server {
        listen 8080;
        server_name _;
        
        # Health check endpoint (HTTP only, no redirect)
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Serve content for MetalLB requests, redirect others
        location / {
            if ($serve_content = 0) {
                return 301 https://p5js-sketches.services.k8s.goldentooth.net$request_uri;
            }
            
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ @sketches;
        }
        
        # Handle sketch subdirectories and fallback to gallery
        location @sketches {
            try_files /$uri/index.html /index.html =404;
        }
    }
    
    server {
        listen 8443 ssl;
        http2 on;
        server_name {{ index .Values.spec.service.annotations "external-dns.alpha.kubernetes.io/hostname" }};
        root /usr/share/nginx/html;
        index index.html;
        
        # SSL configuration
        ssl_certificate /etc/ssl/certs/tls.crt;
        ssl_certificate_key /etc/ssl/private/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers off;
        
        # Health check endpoint (also available on HTTPS)
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Serve sketches from subdirectories
        location / {
            try_files $uri $uri/ =404;
            
            # Cache static assets with shorter duration for development
            location ~* \.(js|css)$ {
                expires 5m;
                add_header Cache-Control "public, max-age=300";
            }
            
            # Cache images longer since they change less frequently
            location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
                expires 1h;
                add_header Cache-Control "public, max-age=3600";
            }
            
            # Special handling for p5.js sketches
            location ~ ^/([^/]+)/?$ {
                try_files $uri $uri/ /$1/index.html =404;
            }
        }
        
        # Serve custom gallery index.html at root
        location = / {
            try_files /index.html =404;
        }
    }