apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5js-sketches
  namespace: {{ .Values.spec.namespace }}
  labels:
    app: p5js-sketches
spec:
  replicas: {{ .Values.spec.server.replicas }}
  selector:
    matchLabels:
      app: p5js-sketches
  template:
    metadata:
      labels:
        app: p5js-sketches
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/health"
    spec:
      serviceAccountName: p5js-sketches-controller
      securityContext:
        runAsNonRoot: {{ .Values.spec.security.runAsNonRoot }}
        runAsUser: {{ .Values.spec.security.runAsUser }}
        runAsGroup: {{ .Values.spec.security.runAsGroup }}
        fsGroup: {{ .Values.spec.security.runAsGroup }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - p5js-sketches
              topologyKey: kubernetes.io/hostname
      initContainers:
      # Sketch sync init container - syncs sketches at startup
      - name: sketch-sync
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          apk add --no-cache curl jq git
          echo "Syncing registered sketches..."
          
          # Get all registration ConfigMaps using kubectl
          kubectl get configmaps -n {{ .Values.spec.namespace }} \
            -l p5js-sketch/registration=true \
            -o json | jq -r '.items[] | 
              "\(.metadata.name)|\(.data."registration.json" | fromjson | .repository)|\(.data."registration.json" | fromjson | .branch // "main")|\(.data."registration.json" | fromjson | .name)"' | \
          while IFS='|' read -r configmap_name repository branch name; do
            if [ -n "$repository" ] && [ -n "$name" ]; then
              target_path="/srv/sketches/$name"
              echo "Syncing $name from $repository ($branch) to $target_path"
              
              # Remove existing directory
              rm -rf "$target_path"
              
              # Clone repository
              git clone --depth 1 --branch "$branch" "$repository" "$target_path" || {
                echo "Failed to clone $repository"
                continue
              }
              
              cd "$target_path"
              rm -rf .git
              
              # Set ownership for nginx
              chown -R 101:101 "$target_path"
              
              # Verify required files
              if [ ! -f "index.html" ] || [ ! -f "sketch.js" ]; then
                echo "WARNING: Required files missing in $name!"
              else
                echo "Successfully synced $name"
              fi
            fi
          done
          
          echo "Sketch sync completed"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        volumeMounts:
        - name: sketches-storage
          mountPath: /srv/sketches
      
      containers:
      # Main nginx server
      - name: nginx
        image: {{ .Values.spec.server.image }}
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: {{ .Values.spec.server.resources.limits.memory }}
            cpu: {{ .Values.spec.server.resources.limits.cpu }}
          requests:
            memory: {{ .Values.spec.server.resources.requests.memory }}
            cpu: {{ .Values.spec.server.resources.requests.cpu }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.spec.security.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.spec.security.readOnlyRootFilesystem }}
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: sketches-storage
          mountPath: /srv/sketches
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: nginx-tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: sketches-storage
        persistentVolumeClaim:
          claimName: sketches-storage
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}