apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spec.releaseName }}
  namespace: {{ .Values.spec.namespace }}
  labels:
    app: {{ .Values.spec.releaseName }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.spec.releaseName }}
  template:
    metadata:
      labels:
        app: {{ .Values.spec.releaseName }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Values.spec.releaseName }}
              topologyKey: kubernetes.io/hostname
      serviceAccountName: {{ .Values.spec.releaseName }}-controller
      securityContext:
        runAsNonRoot: {{ .Values.security.runAsNonRoot }}
        runAsUser: {{ .Values.security.runAsUser }}
        runAsGroup: {{ .Values.security.runAsGroup }}
      initContainers:
      # Sketch sync init container - syncs sketches at startup
      - name: sketch-sync
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
{{ .Files.Get "sync-script.sh" | replace "NAMESPACE_PLACEHOLDER" .Values.spec.namespace | replace "GALLERY_TEMPLATE_PLACEHOLDER" (.Files.Get "gallery-template.html") | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: sketches-storage
          mountPath: /srv/sketches
        - name: tmp
          mountPath: /tmp
      containers:
      - name: nginx
        image: {{ .Values.server.image }}
        ports:
        - containerPort: 80
          name: http
        securityContext:
          allowPrivilegeEscalation: {{ .Values.security.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.security.readOnlyRootFilesystem }}
        volumeMounts:
        - name: sketches-storage
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          requests:
            memory: {{ .Values.server.resources.requests.memory }}
            cpu: {{ .Values.server.resources.requests.cpu }}
          limits:
            memory: {{ .Values.server.resources.limits.memory }}
            cpu: {{ .Values.server.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: sketches-storage
        persistentVolumeClaim:
          claimName: sketches-storage
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp
        emptyDir: {}