apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sketches-shared-storage
  namespace: {{ .Values.spec.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: seaweedfs-storage-rwx
  resources:
    requests:
      storage: 10Gi