apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sketches-shared-storage
  namespace: {{ .Values.spec.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi