apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sketches-storage
  namespace: {{ .Values.spec.namespace }}
spec:
  accessModes:
    - {{ .Values.spec.storage.accessModes }}
  storageClassName: {{ .Values.spec.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.spec.storage.size }}