apiVersion: v1
kind: Service
metadata:
  name: p5js-sketches
  namespace: {{ .Values.spec.namespace }}
  labels:
    app: p5js-sketches
  annotations:
    {{- range $key, $value := .Values.spec.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.spec.service.type }}
  ports:
  - port: {{ .Values.spec.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: p5js-sketches