name: Build and Push Container Image

on:
  push:
    branches:
      - main
    paths:
      - 'sketches/**'
      - 'capture-previews.js'
      - 'gallery-template.html'
      - 'package*.json'
      - 'Dockerfile'
      - '.github/workflows/build-image.yml'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild image'
        required: false
        default: 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate previews and gallery
        env:
          FORCE_REGENERATE: true
        run: npm run build

      - name: Commit generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add files that exist (use find to handle missing files gracefully)
          find sketches -name "preview.png" -o -name "preview.gif" -o -name "metadata.json" | xargs -r git add
          git add sketches/index.html 2>/dev/null || echo "index.html not found"
          
          if ! git diff --cached --quiet; then
            git commit -m "🖼️ Auto-generate gallery and preview files
            
            Generated by build workflow
            - Updated preview images and metadata
            - Regenerated gallery index.html
            
            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate deployment summary
        run: |
          echo "## 🚀 Container Image Built Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta.outputs.tags }}' | sed 's/^/- `/' | sed 's/$/`/' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Ready for deployment to Kubernetes cluster!" >> $GITHUB_STEP_SUMMARY